# Generated by Django 4.2.13 on 2024-05-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutomobilioModelis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marke", models.CharField(max_length=20, verbose_name="Marke")),
                ("modelis", models.CharField(max_length=20, verbose_name="Modelis")),
                ("metai", models.IntegerField(verbose_name="Metai")),
                ("variklis", models.CharField(max_length=3, verbose_name="Variklis")),
            ],
        ),
    ]
