# Generated by Django 4.2.13 on 2024-05-12 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("autoserviceapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paslauga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pavadinimas",
                    models.CharField(max_length=50, verbose_name="pavadinimas"),
                ),
                ("kaina", models.IntegerField(verbose_name="Kaina")),
            ],
        ),
        migrations.CreateModel(
            name="Uzsakymas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                ("suma", models.FloatField(verbose_name="Suma")),
            ],
        ),
        migrations.CreateModel(
            name="UzsakymoEilutes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kiekis", models.IntegerField(verbose_name="Kiekis")),
                ("kaina", models.IntegerField(verbose_name="Kaina")),
            ],
        ),
        migrations.CreateModel(
            name="Automobilis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valstybinis_nr",
                    models.CharField(max_length=6, verbose_name="Valstybinis Nr."),
                ),
                ("vin", models.IntegerField(verbose_name="VIN code")),
                ("klientas", models.CharField(max_length=20, verbose_name="Klientas")),
                (
                    "car_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="autoserviceapp.automobiliomodelis",
                    ),
                ),
            ],
        ),
    ]
