# Generated by Django 4.2.13 on 2024-05-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autoserviceapp", "0003_uzsakymas_car_uzsakymoeilutes_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automobilis",
            name="vin",
            field=models.IntegerField(default=510443830, verbose_name="VIN code"),
        ),
    ]
