# Generated by Django 4.2.13 on 2024-05-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autoserviceapp", "0004_alter_automobilis_vin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automobilis",
            name="vin",
            field=models.IntegerField(default=107751023, verbose_name="VIN code"),
        ),
        migrations.AlterField(
            model_name="paslauga",
            name="kaina",
            field=models.FloatField(verbose_name="Kaina"),
        ),
        migrations.AlterField(
            model_name="uzsakymoeilutes",
            name="kaina",
            field=models.FloatField(verbose_name="Kaina"),
        ),
    ]
