# Generated by Django 4.2.13 on 2024-05-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "autoserviceapp",
            "0007_rename_car_model_automobilis_automobilio_modelis_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uzsakymas",
            name="automobilis",
        ),
        migrations.RemoveField(
            model_name="uzsakymoeilutes",
            name="paslauga",
        ),
        migrations.RemoveField(
            model_name="uzsakymoeilutes",
            name="uzsakymas",
        ),
        migrations.DeleteModel(
            name="Automobilis",
        ),
        migrations.DeleteModel(
            name="Uzsakymas",
        ),
        migrations.DeleteModel(
            name="UzsakymoEilutes",
        ),
    ]
