# Generated by Django 4.2.13 on 2024-05-13 10:47

import autoserviceapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("autoserviceapp", "0008_remove_uzsakymas_automobilis_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Automobilis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valstybinis_nr",
                    models.CharField(max_length=6, verbose_name="Valstybinis Nr."),
                ),
                (
                    "vin",
                    models.IntegerField(
                        default=autoserviceapp.models.make_random_vin,
                        verbose_name="VIN code",
                    ),
                ),
                ("klientas", models.CharField(max_length=20, verbose_name="Klientas")),
                (
                    "automobilio_modelis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="autoserviceapp.automobiliomodelis",
                    ),
                ),
            ],
        ),
    ]
