# Generated by Django 4.2.13 on 2024-05-13 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("autoserviceapp", "0009_automobilis"),
    ]

    operations = [
        migrations.CreateModel(
            name="Uzsakymas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(blank=True, null=True, verbose_name="Data")),
                ("suma", models.FloatField(verbose_name="Suma")),
                (
                    "automobilis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="autoserviceapp.automobilis",
                    ),
                ),
            ],
        ),
    ]
