# Generated by Django 4.2.13 on 2024-05-13 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("autoserviceapp", "0011_uzsakymoeilutes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="automobiliomodelis",
            options={
                "verbose_name": "Automobilio modelis",
                "verbose_name_plural": "Automobilio modeliai",
            },
        ),
        migrations.AlterModelOptions(
            name="automobilis",
            options={
                "verbose_name": "Automobilis",
                "verbose_name_plural": "Automobiliai",
            },
        ),
        migrations.AlterModelOptions(
            name="paslauga",
            options={"verbose_name": "Paslauga", "verbose_name_plural": "Paslaugos"},
        ),
        migrations.AlterModelOptions(
            name="uzsakymas",
            options={"verbose_name": "Uzsakymas", "verbose_name_plural": "Uzsakymai"},
        ),
        migrations.AlterModelOptions(
            name="uzsakymoeilutes",
            options={
                "verbose_name": "Uzsakymo Eilute",
                "verbose_name_plural": "Uzsakymo Eilutes",
            },
        ),
    ]
