# Generated by Django 4.2.13 on 2024-05-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autoserviceapp", "0012_alter_automobiliomodelis_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uzsakymas",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("p", "Priimtas"),
                    ("e", "Eigoje"),
                    ("ap", "Atliktu darbu patikrinimas"),
                    ("i", "Ivykdytas"),
                ],
                default="a",
                help_text="Uzsakymo statusas",
                max_length=2,
            ),
        ),
    ]
