# Generated by Django 4.2.13 on 2024-05-14 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("autoserviceapp", "0013_uzsakymas_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="automobiliomodelis",
            options={
                "ordering": ["marke"],
                "verbose_name": "Automobilio modelis",
                "verbose_name_plural": "Automobilio modeliai",
            },
        ),
    ]
