# Generated by Django 4.2.13 on 2024-05-21 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("autoserviceapp", "0015_automobilis_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="uzsakymas",
            name="grazinimo_terminas",
            field=models.DateField(
                blank=True, null=True, verbose_name="Grazinimo data"
            ),
        ),
        migrations.AddField(
            model_name="uzsakymas",
            name="uzsakovas",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
