# Generated by Django 4.2.13 on 2024-05-21 15:13

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("autoserviceapp", "0016_uzsakymas_grazinimo_terminas_uzsakymas_uzsakovas"),
    ]

    operations = [
        migrations.AddField(
            model_name="automobilis",
            name="aprasymas",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
