# Generated by Django 4.2.13 on 2024-05-23 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("autoserviceapp", "0017_automobilis_aprasymas"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paslauga",
            options={"verbose_name": "Paslauga", "verbose_name_plural": " Paslaugos"},
        ),
        migrations.AlterModelOptions(
            name="uzsakymas",
            options={"verbose_name": "Užsakymas", "verbose_name_plural": "Užsakymai"},
        ),
        migrations.AlterModelOptions(
            name="uzsakymoeilutes",
            options={
                "verbose_name": "Užsakymo Eilutė",
                "verbose_name_plural": "Užsakymo Eilutes",
            },
        ),
        migrations.RemoveField(
            model_name="uzsakymas",
            name="suma",
        ),
        migrations.RemoveField(
            model_name="uzsakymoeilutes",
            name="kaina",
        ),
        migrations.AlterField(
            model_name="automobilis",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="covers", verbose_name="Viršelis"
            ),
        ),
        migrations.AlterField(
            model_name="uzsakymas",
            name="grazinimo_terminas",
            field=models.DateField(
                blank=True, null=True, verbose_name="Gražinimo data"
            ),
        ),
        migrations.AlterField(
            model_name="uzsakymas",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("p", "Priimtas"),
                    ("e", "Eigoje"),
                    ("ap", "Atliktų darbų patikrinimas"),
                    ("i", "Įvykdytas"),
                ],
                default="a",
                help_text="Uzsakymo statusas",
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name="CarReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.TextField(max_length=2000, verbose_name="Atsiliepimas"),
                ),
                (
                    "car",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="autoserviceapp.automobilis",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
