# Generated by Django 4.2.13 on 2024-05-23 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "autoserviceapp",
            "0018_alter_paslauga_options_alter_uzsakymas_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UzsakymasReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.TextField(max_length=2000, verbose_name="Atsiliepimas"),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uzsakymas",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="autoserviceapp.uzsakymas",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CarReview",
        ),
    ]
