# Generated by Django 4.2.13 on 2024-05-24 05:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("autoserviceapp", "0020_progile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Progile",
            new_name="Profile",
        ),
    ]
